name: Release

on:
    push:
        tags:
            - 'v*'

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout del código
              uses: actions/checkout@v4

            - name: Build del component
              run: mvnw clean install -DskipTests

            - name: Crear release en Github
              uses: softprops/action-gh-release@v2
              with:
                name: "Release ${{ github.ref_name }}"
                body: "Release automático generado por Github Actions"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Subir artefacto al release
              uses: softprops/action-gh-release@v2
              with:
                files: |
                    target/*jar
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}