name: Release

on:
    push:
        tags:
            - 'v*'

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout del código
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
              
            - name: Dar permisos de ejecución al wrapper 
              run: chmod +x ./mvnw

            - name: Build del component
              run: ./mvnw clean install -DskipTests

            - name: Crear  y subir artefacto al release en Github
              uses: softprops/action-gh-release@v2
              with:
                name: "Release ${{ github.ref_name }}"
                body: "Release automático generado por Github Actions"
                files: |
                    target/*jar
              env:
                GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}